name: Fetch Issues
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch issues
        uses: githubocto/flat@v2
        with:
          http_url: https://api.github.com/repos/alienzhou/blog/issues?per_page=100&sort=created&filter=all&direction=desc&page=1
          downloaded_filename: public/issues.json
